[package]
name = "rdedup"
version = "0.1.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]

[[bin]]
name = "rdedup"
path = "src/bin.rs"

[dependencies]
rdedup-lib = { path = "lib" }
log = "*"
rustc-serialize = "*"
argparse = "*"
env_logger = "*"
